# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxbeAgZbabJCnUVbGD1lkYCUFDuuV6eo
"""

import math

N = int(input("Digite um valor: "))
def RaizQuadrada(x):
    s = int(math.sqrt(x))
    return s*s == x

def verificaFibonacci(n):

    return RaizQuadrada(5*n*n + 4) or RaizQuadrada(5*n*n - 4)

for i in range(1, N+1):
    if (verificaFibonacci(i) == True):
        print(i, "Esse valor pertence a sequencia de Fibonacci")
    else:
        print(i, "Esse nao valor pertence a sequencia de Fibonacci")