# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixky3QDsZzwGoi1EZwBgHRPs9ItnPa_i
"""

def verificar_letra_a(string):
    contagem_a = string.lower().count('a')

    if contagem_a > 0:
        print(f"A letra 'a' aparece {contagem_a} vez(es) na string.")
    else:
        print("A letra 'a' não foi encontrada na string.")

string_exemplo = input("Digite uma palavra: ")
verificar_letra_a(string_exemplo)